/**
 * BATON dispatch — executor/cerebras.js
 *
 * Cerebras-specific execution adapter. `@cerebras/cerebras_cloud_sdk` is
 * generated by the same Stainless toolchain as `@anthropic-ai/sdk`,
 * `openai`, and `groq-sdk`, and exposes the identical error-class hierarchy
 * (verified below), so this adapter mirrors anthropic.js/openai.js/groq.js
 * exactly: constructor-injected client, same call signature, same return
 * shape.
 *
 * REAL SHAPE OBSERVED (not assumed from docs) — captured by constructing a
 * real Cerebras client with a garbage API key and making one real network
 * call against `chat.completions.create()`, 2026-08-29:
 *
 * Cerebras (`@cerebras/cerebras_cloud_sdk@1.91.0`), 401 on `chat.completions.create()`:
 *   constructor.name              -> "AuthenticationError"
 *   err instanceof Cerebras.AuthenticationError -> true
 *   err instanceof Cerebras.APIError            -> true
 *   err.status                    -> 401
 *   err.message                   -> '401 Wrong API Key'
 *   err.error (parsed body)        -> { message: "Wrong API Key", type: "invalid_request_error", param: "api_key", code: "wrong_api_key" }
 *   own enumerable keys           -> status, headers, error
 *
 * The SDK's `error.d.ts` exports the same five classes anthropic.js /
 * openai.js / groq.js classify against, so the shared `classifyError()`
 * from ./errors.js is reused unmodified.
 *
 * MODEL AVAILABILITY NOTE (2026-08-29): the task brief for this adapter
 * named `llama-3.3-70b` as Cerebras's expected free-model default. As of
 * this check, Cerebras's public model catalog (inference-docs.cerebras.ai
 * /models/overview) no longer lists ANY Llama model — the current public
 * catalog is `gpt-oss-120b` and `gemma-4-31b` only. `gpt-oss-120b` is used
 * below as the closest current substitute (120B params, ~3000 tok/s, the
 * larger of the two free models). This is a real, observed catalog change,
 * not a guess — re-check inference-docs.cerebras.ai/models/overview before
 * relying on this default long-term, as this catalog has moved fast.
 */

import Cerebras from '@cerebras/cerebras_cloud_sdk';
import { classifyError } from './errors.js';

/** The provider name this adapter registers under in executor/index.js. */
export const PROVIDER_NAME = 'cerebras';

/** Override with `BATON_DISPATCH_CEREBRAS_MODEL` env var. See the
 * MODEL AVAILABILITY NOTE above — llama-3.3-70b has been removed from
 * Cerebras's public catalog; gpt-oss-120b is the current substitute. */
export const DEFAULT_MODEL = process.env.BATON_DISPATCH_CEREBRAS_MODEL || 'gpt-oss-120b';

/** The error classes this adapter classifies against — real exports of the
 * installed `@cerebras/cerebras_cloud_sdk`, never re-declared or guessed. */
const ERROR_CLASSES = {
  AuthenticationError: Cerebras.AuthenticationError,
  RateLimitError: Cerebras.RateLimitError,
  APIConnectionTimeoutError: Cerebras.APIConnectionTimeoutError,
  APIConnectionError: Cerebras.APIConnectionError,
  APIError: Cerebras.APIError
};

/**
 * Build a real client. Zero-arg by default — the SDK resolves
 * `CEREBRAS_API_KEY` from the environment rather than hardcoding a key.
 */
export function createClient(options = {}) {
  return new Cerebras(options);
}

/**
 * Call `chat.completions.create()` and return the plain-text output plus
 * the ACTUAL token usage measured from the response — never the predicted
 * `expectedTokens` from route-contracts.js's heuristic.
 *
 * Cerebras's OpenAI-compatible `usage` object reports `prompt_tokens`,
 * `completion_tokens`, and `total_tokens` — identical shape to openai.js.
 *
 * @param {Cerebras} client
 * @param {string} prompt
 * @param {{ model?: string, maxTokens?: number, timeoutMs?: number }} [opts]
 * @returns {Promise<{ text: string, actualTokens: number, raw: object }>}
 */
export async function callCerebras(client, prompt, opts = {}) {
  const { model = DEFAULT_MODEL, maxTokens = 4096, timeoutMs } = opts;

  const requestOptions = Number.isFinite(timeoutMs) ? { timeout: timeoutMs } : undefined;

  const response = await client.chat.completions.create(
    {
      model,
      max_tokens: maxTokens,
      messages: [{ role: 'user', content: prompt }]
    },
    requestOptions
  );

  const text = response.choices?.[0]?.message?.content ?? '';

  const usage = response.usage ?? {};
  const actualTokens = usage.total_tokens ?? (usage.prompt_tokens ?? 0) + (usage.completion_tokens ?? 0);

  return { text, actualTokens, raw: response };
}

/** Classify a thrown Cerebras SDK error into the shared outcome shape. */
export function classifyCerebrasError(err) {
  return classifyError(err, ERROR_CLASSES);
}
