/**
 * BATON dispatch — executor/errors.js
 *
 * Shared error classification for provider execution adapters. Anthropic's
 * and OpenAI's SDKs happen to export an identically-named error class
 * hierarchy (`AuthenticationError`, `RateLimitError`,
 * `APIConnectionTimeoutError`, `APIConnectionError`, `APIError` — all
 * generated by the same Stainless SDK generator), so one classifier works
 * for both: each adapter passes in ITS OWN imported classes (dependency
 * injection, same pattern as swarm/lib/client.js), never a shared import of
 * one SDK's classes applied to the other's errors.
 *
 * REAL SHAPES OBSERVED (not assumed from docs) — captured by constructing a
 * real Anthropic client and a real OpenAI client with a garbage API key and
 * making one real network call against each, 2026-08-29:
 *
 * Anthropic (`@anthropic-ai/sdk@0.122.0`), 401 on `messages.create()`:
 *   constructor.name              -> "AuthenticationError"
 *   err instanceof Anthropic.AuthenticationError -> true
 *   err instanceof Anthropic.APIError            -> true
 *   err.status                    -> 401
 *   err.message                   -> '401 {"type":"error","error":{"type":"authentication_error","message":"API key is invalid."},"request_id":null}'
 *   err.error (parsed body)        -> { type: "error", error: { type: "authentication_error", message: "API key is invalid." }, request_id: null }
 *   own enumerable keys           -> status, headers, requestID, workspaceID, error, type
 *
 * OpenAI (`openai@4.104.0`), 401 on `chat.completions.create()`:
 *   constructor.name              -> "AuthenticationError"
 *   err instanceof OpenAI.AuthenticationError -> true
 *   err instanceof OpenAI.APIError            -> true
 *   err.status                    -> 401
 *   err.message                   -> '401 Incorrect API key provided: sk-garba****...0000. You can find your API key at https://platform.openai.com/account/api-keys.'
 *   err.error (parsed body)        -> { message: "Incorrect API key provided: ...", type: "invalid_request_error", code: "invalid_api_key", param: null }
 *   own enumerable keys           -> status, headers, request_id, error, code, param, type
 *
 * Two things this measurement actually changed vs. assumption:
 *  1. In these installed SDK versions, `instanceof AuthenticationError` DOES
 *     correctly match a real auth failure for both providers — this is NOT
 *     a repeat of the baton-swarm bug (a plain `Error` that failed an
 *     `instanceof` check against the SDK's real shape). Good to confirm,
 *     not to assume: a future SDK bump could change this again, which is
 *     exactly why this classifier is tested against real constructed error
 *     instances below, not just trusted from this comment.
 *  2. OpenAI's own error BODY reports `type: "invalid_request_error"` even
 *     for an authentication failure — the body-level `type` field is NOT a
 *     reliable way to detect an auth error for OpenAI. Classification here
 *     always uses `instanceof` / `err.status`, never `err.error.type`
 *     string-matching, for exactly this reason.
 */

/** @typedef {'success'|'quota_exceeded'|'timeout'|'error'} ExecutionStatus */

export const EXECUTION_STATUS = Object.freeze({
  SUCCESS: 'success',
  QUOTA_EXCEEDED: 'quota_exceeded',
  TIMEOUT: 'timeout',
  ERROR: 'error'
});

/**
 * Classify a thrown SDK error into the outcome shape the ledger/reputation
 * loop depends on. `sdkErrors` is the provider-specific bag of error
 * classes (see anthropic.js / openai.js) — never hardcoded here, so this
 * function has no dependency on either SDK package directly and can be
 * exercised in tests with any object shaped like `{ AuthenticationError,
 * RateLimitError, APIConnectionTimeoutError, APIConnectionError, APIError }`.
 *
 * `status` stays within the Outcome schema's 4-value enum
 * (PRODUCT-ARCHITECTURE.md `actual_metrics.status`), but authentication
 * failures and generic API errors both land on `status: 'error'` — they are
 * still told apart via `errorClass`, which is the field the reputation loop
 * must actually branch on. Conflating "bad credentials" with "malformed
 * request" into one undifferentiated `error` string was the exact failure
 * mode this task was written to avoid, so `errorClass` is not optional
 * metadata here — it is the real classification signal.
 *
 * @returns {{ status: ExecutionStatus, errorClass: string, errorDetail: string }}
 */
export function classifyError(err, sdkErrors = {}) {
  const {
    AuthenticationError,
    RateLimitError,
    APIConnectionTimeoutError,
    APIConnectionError,
    APIError
  } = sdkErrors;

  const message = err?.message ?? String(err);

  // Order matters: APIConnectionTimeoutError extends APIConnectionError
  // extends APIError in both SDKs, so the most specific class must be
  // checked first or a timeout would be caught by the generic APIError
  // branch below.
  if (APIConnectionTimeoutError && err instanceof APIConnectionTimeoutError) {
    return { status: EXECUTION_STATUS.TIMEOUT, errorClass: 'APIConnectionTimeoutError', errorDetail: message };
  }

  if (RateLimitError && err instanceof RateLimitError) {
    return { status: EXECUTION_STATUS.QUOTA_EXCEEDED, errorClass: 'RateLimitError', errorDetail: message };
  }

  if (AuthenticationError && err instanceof AuthenticationError) {
    return { status: EXECUTION_STATUS.ERROR, errorClass: 'AuthenticationError', errorDetail: message };
  }

  if (APIConnectionError && err instanceof APIConnectionError) {
    return { status: EXECUTION_STATUS.ERROR, errorClass: 'APIConnectionError', errorDetail: message };
  }

  if (APIError && err instanceof APIError) {
    // A generic/other API error: bad request, permission denied, not found,
    // conflict, unprocessable entity, internal server error, or any status
    // the SDK didn't have a named subclass for. Preserve the SDK's own
    // constructor name (e.g. "BadRequestError", "InternalServerError")
    // rather than collapsing it to "APIError" — the actual subclass is a
    // more useful reputation/fallback signal than the base class.
    return { status: EXECUTION_STATUS.ERROR, errorClass: err.constructor?.name ?? 'APIError', errorDetail: message };
  }

  // Not an SDK error at all (a bug in our own request-shaping code, a
  // plain network-stack throw, etc.) — still classified as 'error', never
  // silently swallowed, but flagged distinctly so it isn't mistaken for a
  // provider-side signal.
  return { status: EXECUTION_STATUS.ERROR, errorClass: err?.constructor?.name ?? 'UnknownError', errorDetail: message };
}
